name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 8.0, 8.1]
        laravel: [9.*, 10.*]
        stability: [prefer-stable]
        exclude:
          -   php: 7.4
              laravel: 10.*
          -   php: 8.0
              laravel: 10.*
          -   php: 7.4
              laravel: 9.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, intl, gd, exif, iconv
            coverage: none
      -   name: Install dependencies
          run: |
            composer install
            composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      -   name: Execute tests
          run: vendor/bin/phpunit
